### ISSUE TITLE
Metadata of generated api documentation is hardcoded

### ISSUE THREAD

**Issue by doomsju** [Informatievlaanderen/swagger#4]
![image (2)](https://user-images.githubusercontent.com/44768943/67274641-277ed600-f4c1-11e9-9956-6ae6632ceaff.png)
![image (3)](https://user-images.githubusercontent.com/44768943/67274666-382f4c00-f4c1-11e9-9bdd-798560fafb84.png)

**Comment by CumpsD** [comment]
👍 Something we overlooked, will fix asap

**Comment by CumpsD** [comment]
New options you can set:
* `DocumentDescriptionFunc`
* `ApplicationNameFunc`

The `manifest.json` is also properly updated now.
